name: PHPUnit

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: punksolid_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@master
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Start MYSQL Service
      run: |
          sudo /etc/init.d/mysql start
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies
      run: composer install
#      run: composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
#    - name: Verify MySQL connection from host
#      run: |
#        sudo apt-get install -y mysql-client
#        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_DATABASE: punksolid_test
      run: php artisan migrate:fresh --seed && vendor/bin/phpunit --testdox
